services:
  web:
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 5500
    build: .
    ports:
      - 5500:5500
    env_file:
      - ".env"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - redis:/root/redis

volumes:
  redis:
